package com.nox.gpacalculator

class MapClass {

    val moduleMap = mapOf<String,String>("LS" to "Listening & Speaking", "RW" to "Reading & Writing",
        "C prog" to "C programming" ,"Probab and Stats" to "Probabilities and Statistics",
        "Adv Diff Equations" to "Advanced Differential Equation","Complex Variable" to "Complex Variable",
        "Digital Control" to "Digital Control","Power Eng" to "Power Eng. Materials","C & S" to "Computation and Simulation using Matlab" ,
        "D.S.P" to "Digital Signal Processing","Num Methods" to "Numerical Methods",
        "Elec Machines" to "Electric Machines","P.S.A" to "Power System Analysis",
        "Power Electro" to "Power Electronics","Network Analysis" to "Network Analysis and Synthesis",
        "Num Methods Lab" to "Numerical methods Lab","P.S.A Lab" to "Power System Analysis Lab",
        "Elec Machines Lab" to "Electric Machines lab","Power Electro Lab" to "Power Electronics Lab",
        "Adv E.F.T" to "Advanced Electromagnetic Field Theory","Microwave Eng" to "Microwave Engineering",
        "Radio Wave" to "Radio Wave Propagation","Adv Communications" to "Advanced Communications",
        "Antennas" to "Antennas","O.F.C Sys" to "Optical Fiber Communication Systems",
        "Electrical Networks" to "Electrical Networks Analysis","Antennas Lab" to "Antennas Lab",
        "P.S.P" to "Probability and stochastic processes","Digital cont sys" to "Digital control systems",
        "D.C.I" to "Digital controllers implementations","Scientific Comput" to "Introduction to scientific computing with MATLAB",
        "Industrial Auto" to "Industrial Automation","Multivar Cont sys" to "Multivariable Control Systems",
        "D.S & algo" to "Data Structures and Algorithms","Indust Auto Lab" to "Industrial Automation lab",
        "D.S & algo Lab" to "Data Structures and Algorithms Lab","A.D.S" to "Advanced Digital Systems",
        "Adv prog Lab" to "Advanced Programming Lab","A.D.S Lab" to "Advanced Digital Systems Lab",
        "Adv IC's" to "Advanced IC’s","D.S & Algo" to "Data Structures and Algorithms",
        "Adv IC's Lab" to "Advanced IC's Lab","Operating sys Lab" to "Operating Systems Lab",
        "P.S.C" to "Power System Control and Operation","Protective Systems" to "Instrumentation and Protective Systems",
        "R.A.M & Security" to "Reliability, Availability, Maintainability and Security","Programmable Dev" to "Instrumentation and Programmable Devices",
        "I.P.N" to "Industrial Power Network","P.S.C Lab" to "Power System Control and Operation Lab",
        "Information Theory" to "Information Theory and Coding","R.F Design" to "RF and Microwave Circuits Design",
        "Radar & Satellite.." to "Radar and Satellite Communication Systems","Networks & Proto.. Lab" to "Networks and Protocols Lab",
        "Project" to "Final Project","C.S" to "Communication Skills",
        "Management" to "Project Management","Optimal cont Sys" to "Optimal control Systems",
        "Nonlinear Sys" to "Nonlinear Systems and control","S.I" to "System Identification",
        "I.I" to "Industrial instrumentation","I.I Lab" to "Industrial instrumentation laboartory",
        "F.D & isolation" to "fault detection & isolation" ,"Embedded Sys" to "Embedded Systems",
        "D.S.P " to "Digital Signal Processing with Applications","Prog Languages" to "Programming Languages",
        "Computer Net" to "Computer Networks","Computer Net Lab" to "Computer Networks Lab",
        "Intro to UML" to "Introduction to UML","Adv Maths" to "Advanced Mathematics",
        "Operating sys" to "Operating Systems","Embedded Sys Lab" to "Embedded Systems Lab",
        "Probab & Stats" to "Probability and Statistics","Adv Commun.." to "Advanced Communications",
        "Image Process Lab" to "Image Processing Lab",
        "comp arch" to "Computer Architecture",
        "C.P" to "Communication Principles",
        "M.S.D" to "Microprocessor System Design",
        "Power Electro" to "Power Electronics",
        "Linear Sys" to "Linear Systems",
        "Process Cont" to "Process Control & Instrumentation",
        "C.P  Lab" to "Communication Principles Lab",
        "C.C" to "Communication Circuits",
        "Energy Sys" to "Energy Systems",
        "L.C.S" to "Linear Control Systems",
        "Diff equations" to "Differential Equations",
        "Digital Sys" to "Digital Systems",
        "Active Dev" to "Active Devices",
        "Eng Economics" to "Engineering Economics",
        "Electromag" to "Electromagnetic Theory",
        "Linear Sys" to "Linear Systems",
        "Elec Machines" to "Electrical Machines",
        "C.C  Lab" to "Communication Circuits Lab",
        "Eng Management" to "Engineering Management",
        "L.C.S Lab" to "Linear Control Systems Lab",

        )
}